--- 
extensions: 
- json
- another-extension
- gps
- camera
name: rhomobile-quiz
capabilities: 
- camera
- gps
bbver: 4.6
android: 
  extensions: 
  - barcode
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.2.0
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.2.0
iphone: 
  extensions: 
  - barcode
  provisionprofile: 
  sdk: iphonesimulator4.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
  emulator: 4.0.1
