--- 
name: rhomobile-quiz
extensions: 
- json
- another-extension
- gps
- camera
capabilities: 
- camera
- gps
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.2.1
android: 
  extensions: 
  - barcode
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.2.1
vendor: rhomobile
iphone: 
  provisionprofile: 
  extensions: 
  - barcode
  sdk: iphonesimulator4.1
  codesignidentity: 
  entitlements: 
  configuration: Debug
  emulator: 4.1
